version: "2"
services:
  web:
    build: ./service/dor-http/
    restart: always
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      DOR_STORAGE_URL: "tcp://clickhouse:9000"
      DOR_STORAGE: "clickhouse"
      DOR_PORT: "8080"

  insert:
    build: ./cmd/dor-insert/
    restart: always
    depends_on:
      - clickhouse
    environment:
      DOR_STORAGE_URL: "tcp://clickhouse:9000"
      DOR_STORAGE: "clickhouse"

  clickhouse:
    restart: always
    image: yandex/clickhouse-server:latest
    volumes:
      - ./storage:/var/lib/clickhouse
