version: "2"
services:
  web:
    image: ilyaglow/dor-web-mongo
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      DOR_MONGO_URL: "mongo"
      DOR_PORT: "8080"

  insert:
    image: ilyaglow/dor-insert-mongo
    restart: always
    depends_on:
      - mongo
    environment:
      DOR_MONGO_URL: "mongo"

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - ./mongodata:/data/db
