version: "2"
services:
  web:
    build:
      context: .
      dockerfile: dor-http.Dockerfile
    restart: always
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      DOR_STORAGE_URL: "tcp://clickhouse:9000"
      DOR_STORAGE: "clickhouse"

  insert:
    build:
      context: .
      dockerfile: dor-insert.Dockerfile
    restart: always
    depends_on:
      - clickhouse
    environment:
      DOR_STORAGE_URL: "tcp://clickhouse:9000"
      DOR_STORAGE: "clickhouse"

  clickhouse:
    restart: always
    image: yandex/clickhouse-server:latest
    volumes:
      - ./storage:/var/lib/clickhouse
